#!/usr/bin/env bash

#===================================================================================
#                          Import tools library
#===================================================================================
. "$(packagerepo --lib)"

#===================================================================================
#                              Logging Options
#===================================================================================
logging::set_severity info

#===================================================================================
#                              Help Message
#===================================================================================
showhelp() {
    local _synopsis="
        Pypi repository service
    "

    local -A _keywords=(
        [folder]="Path for the repo"
        [version]="Produce the version string"
        [allow]="Network to allow connections from"
        [port]="TCP Port to listen on"
        [help]="Display instructions"
    )

    local _terms="$(echo "${@}" | awk -F, '{for (i=1; i <= NF; ++i) {print $i;}}' | sed -e 's/[\:]*$//g')"
    local _topic

    local _contents="$(
        echo "${_terms}" | awk -F: '{printf("%s[--%s%s]", sep, $1, (NF == 2 ? sprintf("=<%s>", $1) : "")); sep=" "}'
        echo -en "${_synopsis:+\n}"
        echo "${_synopsis}" | sed -e 's/^[ ]*//g' -e '/^[ ]*$/d'

        echo "${_terms}" | {
            _prefix="\n"

            while read _topic
            do
                if [ -n "${_keywords["${_topic}"]}" ]
                then
                    _fill="$(for ((i=$(echo -n "${_topic}" | wc -c); i < 15; ++i)); do echo -n " "; done)"
                    echo -e "${_prefix}--${_topic}${_fill}${_keywords["${_topic}"]}" | sed -e 's/^./    &/g'
                    _prefix=""
                fi
            done
        }
    )"

    echo "Usage: $0 ${_contents}" >&2
}

#===================================================================================
# NOTE: There is a bug in getopts where not specifying at least one short option
#       will cause the first non option parameter to be discarded. Here, we just
#       use -h (help)
#===================================================================================
long_options="help,version,debug,info,warning,error,fatal,folder::,repo::,port:,allow:"

OPTION_TEMP=$(getopt -a -o hv --long ${long_options} -- "$@")

if [ $? != 0 ]
then
    logging::fatal "Invalid command line options ${OPTION_TEMP}"
fi

eval set -- "$OPTION_TEMP"

#===================================================================================
#                       Process command line parameters
#
# NOTE: The command line parameters are available for scripts which
#       source this file.
#===================================================================================
port=17171
allowed_addr=()

while true
do
    case "$1" in
        --debug|--info|--warning|--error|--fatal)
            logging::set_severity "$(echo "${1}" | sed -e 's/^[\-]*//g')"
            shift
            ;;

        --allow)
            allowed_addr[${#allowed_addr[@]}]="${2}"
            shift 2
            ;;

        --port)
            port="$2"
            shift 2
            ;;

        --repo|--folder)
            if [ -z "${2}" ]
            then
                package_repo::repository::path
            else
                package_repo::repository::path "${2}"
            fi

            shift 2
            ;;

        --version)
            package_repo::version
            exit 0
            ;;

        --)
            shift
            break
            ;;

        *)
            showhelp "${long_options}" >&2
            exit 0
            ;;
    esac
done

#===================================================================================
#                            Setup
#===================================================================================
tools_folder="$(package_repo::tools::path)"
modules_folder="$(package_repo::modules::path)"

#===================================================================================
#
#===================================================================================
${tools_folder}/webserve \
    $(
        for ((_index=0; _index <= ${#allowed_addr[@]}; ++_index))
        do
            echo " --allow=${allowed_addr[${_index}]}"
        done
    ) \
    --module="${modules_folder}/pypi" \
    --port=${port}
